package main;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MBEAH
 */
public class DispatchAccount extends javax.swing.JFrame {

    public static String APP_TITLE = "Greenwich Cabs";//Title for window
    private String dispatchUsername = "";//the dispatch username, to be received from calling class
    private String dispatchName = "";//the dispatch id, to be received from calling class
    
    /**
     * Default constructor sets window title and initializes components
     */
    public DispatchAccount() {
        this.setTitle(APP_TITLE);
        initComponents();
    }
    
    /**
     * Constructor that takes a string parameter
     * @param Id the username of the dispatcher
     * @param name the name of the dispatcher
     */
    public DispatchAccount(String Id, String name) {
        dispatchUsername = Id;
        dispatchName = name;
        this.setTitle(APP_TITLE);
        initComponents();
        dispatchLabel.setText(dispatchName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addJourneyButton = new javax.swing.JButton();
        viewJourneyButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        errorTextLabel = new javax.swing.JLabel();
        dispatchLabel = new javax.swing.JLabel();
        viewTotals = new javax.swing.JButton();
        newDriverButton = new javax.swing.JButton();
        newDispatchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GREENWICH CABS");

        jLabel2.setText("DISPATCHER:");

        addJourneyButton.setText("ADD NEW JOURNEY");
        addJourneyButton.setMaximumSize(null);
        addJourneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJourneyButtonActionPerformed(evt);
            }
        });

        viewJourneyButton.setText("VIEW / EDIT JOURNEYS");
        viewJourneyButton.setMinimumSize(new java.awt.Dimension(129, 23));
        viewJourneyButton.setPreferredSize(new java.awt.Dimension(129, 23));
        viewJourneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJourneyButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        dispatchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dispatchLabel.setForeground(new java.awt.Color(0, 153, 51));

        viewTotals.setText("VIEW TOTALS");
        viewTotals.setMaximumSize(null);
        viewTotals.setMinimumSize(new java.awt.Dimension(129, 23));
        viewTotals.setPreferredSize(new java.awt.Dimension(129, 23));
        viewTotals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTotalsMouseClicked(evt);
            }
        });

        newDriverButton.setText("ADD NEW DRIVER");
        newDriverButton.setMaximumSize(null);
        newDriverButton.setMinimumSize(new java.awt.Dimension(129, 23));
        newDriverButton.setPreferredSize(new java.awt.Dimension(129, 23));
        newDriverButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newDriverButtonMouseClicked(evt);
            }
        });

        newDispatchButton.setText("ADD NEW DISPATCHER");
        newDispatchButton.setMaximumSize(null);
        newDispatchButton.setMinimumSize(new java.awt.Dimension(129, 23));
        newDispatchButton.setPreferredSize(new java.awt.Dimension(129, 23));
        newDispatchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newDispatchButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dispatchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addComponent(logoutButton))
                    .addComponent(errorTextLabel)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addJourneyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(viewTotals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newDispatchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewJourneyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(newDriverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(logoutButton)
                    .addComponent(dispatchLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addJourneyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(viewJourneyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewTotals, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(newDriverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(newDispatchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //add journey button listener
    private void addJourneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJourneyButtonActionPerformed
        // TODO add your handling code here:
//        errorTextLabel.setText("Some Error Text");
        new NewJourney(dispatchUsername,dispatchName).setVisible(true);
    }//GEN-LAST:event_addJourneyButtonActionPerformed

    //view journey button listener
    private void viewJourneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJourneyButtonActionPerformed
        // TODO add your handling code here:
        new ViewJourneys(dispatchUsername, dispatchName).setVisible(true);
    }//GEN-LAST:event_viewJourneyButtonActionPerformed

    //logout button listener
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        new DispatcherLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void viewTotalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTotalsMouseClicked
        // TODO add your handling code here:
        new ViewTotals(dispatchUsername, dispatchName).setVisible(true);
    }//GEN-LAST:event_viewTotalsMouseClicked

    private void newDispatchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newDispatchButtonMouseClicked
        // TODO add your handling code here:
         new NewDispatcher(dispatchUsername, dispatchName).setVisible(true);
    }//GEN-LAST:event_newDispatchButtonMouseClicked

    private void newDriverButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newDriverButtonMouseClicked
        // TODO add your handling code here:
        new NewDriver(dispatchUsername, dispatchName).setVisible(true);
    }//GEN-LAST:event_newDriverButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DispatchAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DispatchAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DispatchAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DispatchAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DispatchAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJourneyButton;
    private javax.swing.JLabel dispatchLabel;
    private javax.swing.JLabel errorTextLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton newDispatchButton;
    private javax.swing.JButton newDriverButton;
    private javax.swing.JButton viewJourneyButton;
    private javax.swing.JButton viewTotals;
    // End of variables declaration//GEN-END:variables
}
